package com.waveset.adapter.ca;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Sep 24 10:58:37 CEST 2009
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", name = "USD_WebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface USDWebServiceSoap {

    @ResponseWrapper(localName = "getWorkFlowTemplatesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetWorkFlowTemplatesResponse")
    @RequestWrapper(localName = "getWorkFlowTemplates", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetWorkFlowTemplates")
    @WebResult(name = "getWorkFlowTemplatesReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getWorkFlowTemplates(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes
    );

    @ResponseWrapper(localName = "getBookmarksResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetBookmarksResponse")
    @RequestWrapper(localName = "getBookmarks", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetBookmarks")
    @WebResult(name = "getBookmarksReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getBookmarks(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contactId", targetNamespace = "")
        java.lang.String contactId
    );

    @ResponseWrapper(localName = "getLrelValuesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetLrelValuesResponse")
    @RequestWrapper(localName = "getLrelValues", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetLrelValues")
    @WebResult(name = "getLrelValuesReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getLrelValues(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contextObject", targetNamespace = "")
        java.lang.String contextObject,
        @WebParam(name = "lrelName", targetNamespace = "")
        java.lang.String lrelName,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "endIndex", targetNamespace = "")
        int endIndex,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes
    );

    @ResponseWrapper(localName = "removeMemberFromGroupResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.RemoveMemberFromGroupResponse")
    @RequestWrapper(localName = "removeMemberFromGroup", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.RemoveMemberFromGroup")
    @WebMethod
    public void removeMemberFromGroup(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contactHandle", targetNamespace = "")
        java.lang.String contactHandle,
        @WebParam(name = "groupHandle", targetNamespace = "")
        java.lang.String groupHandle
    );

    @ResponseWrapper(localName = "getPropertyInfoForCategoryResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPropertyInfoForCategoryResponse")
    @RequestWrapper(localName = "getPropertyInfoForCategory", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPropertyInfoForCategory")
    @WebResult(name = "getPropertyInfoForCategoryReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getPropertyInfoForCategory(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "categoryHandle", targetNamespace = "")
        java.lang.String categoryHandle,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes
    );

    @ResponseWrapper(localName = "createWorkFlowTaskResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateWorkFlowTaskResponse")
    @RequestWrapper(localName = "createWorkFlowTask", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateWorkFlowTask")
    @WebMethod
    public void createWorkFlowTask(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "attrVals", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attrVals,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "creatorHandle", targetNamespace = "")
        java.lang.String creatorHandle,
        @WebParam(name = "selectedWorkFlow", targetNamespace = "")
        java.lang.String selectedWorkFlow,
        @WebParam(name = "taskType", targetNamespace = "")
        java.lang.String taskType,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes,
        @WebParam(mode = WebParam.Mode.INOUT, name = "createWorkFlowTaskResult", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> createWorkFlowTaskResult,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newHandle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newHandle
    );

    @ResponseWrapper(localName = "deleteBookmarkResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DeleteBookmarkResponse")
    @RequestWrapper(localName = "deleteBookmark", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DeleteBookmark")
    @WebResult(name = "deleteBookmarkReturn", targetNamespace = "")
    @WebMethod
    public int deleteBookmark(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contactId", targetNamespace = "")
        java.lang.String contactId,
        @WebParam(name = "docId", targetNamespace = "")
        int docId
    );

    @ResponseWrapper(localName = "getFolderInfoResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetFolderInfoResponse")
    @RequestWrapper(localName = "getFolderInfo", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetFolderInfo")
    @WebResult(name = "getFolderInfoReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getFolderInfo(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "folderId", targetNamespace = "")
        int folderId
    );

    @ResponseWrapper(localName = "createAttachmentResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateAttachmentResponse")
    @RequestWrapper(localName = "createAttachment", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateAttachment")
    @WebResult(name = "createAttachmentReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String createAttachment(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "repositoryHandle", targetNamespace = "")
        java.lang.String repositoryHandle,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName
    );

    @ResponseWrapper(localName = "createAssetParentChildRelationshipResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateAssetParentChildRelationshipResponse")
    @RequestWrapper(localName = "createAssetParentChildRelationship", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateAssetParentChildRelationship")
    @WebResult(name = "createAssetParentChildRelationshipReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String createAssetParentChildRelationship(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "parentHandle", targetNamespace = "")
        java.lang.String parentHandle,
        @WebParam(name = "childHandle", targetNamespace = "")
        java.lang.String childHandle
    );

    @ResponseWrapper(localName = "createAttmntResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateAttmntResponse")
    @RequestWrapper(localName = "createAttmnt", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateAttmnt")
    @WebResult(name = "createAttmntReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String createAttmnt(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "repositoryHandle", targetNamespace = "")
        java.lang.String repositoryHandle,
        @WebParam(name = "folderId", targetNamespace = "")
        int folderId,
        @WebParam(name = "objectHandle", targetNamespace = "")
        int objectHandle,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName
    );

    @ResponseWrapper(localName = "loginServiceManagedResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.LoginServiceManagedResponse")
    @RequestWrapper(localName = "loginServiceManaged", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.LoginServiceManaged")
    @WebResult(name = "loginServiceManagedReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String loginServiceManaged(
        @WebParam(name = "policy", targetNamespace = "")
        java.lang.String policy,
        @WebParam(name = "encrypted_policy", targetNamespace = "")
        java.lang.String encryptedPolicy
    );

    @ResponseWrapper(localName = "doSelectKDResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DoSelectKDResponse")
    @RequestWrapper(localName = "doSelectKD", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DoSelectKD")
    @WebResult(name = "doSelectKDReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String doSelectKD(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "whereClause", targetNamespace = "")
        java.lang.String whereClause,
        @WebParam(name = "sortBy", targetNamespace = "")
        java.lang.String sortBy,
        @WebParam(name = "desc", targetNamespace = "")
        boolean desc,
        @WebParam(name = "maxRows", targetNamespace = "")
        int maxRows,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes,
        @WebParam(name = "skip", targetNamespace = "")
        int skip
    );

    @ResponseWrapper(localName = "createActivityLogResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateActivityLogResponse")
    @RequestWrapper(localName = "createActivityLog", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateActivityLog")
    @WebResult(name = "createActivityLogReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String createActivityLog(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "logType", targetNamespace = "")
        java.lang.String logType,
        @WebParam(name = "timeSpent", targetNamespace = "")
        int timeSpent,
        @WebParam(name = "internal", targetNamespace = "")
        boolean internal
    );

    @ResponseWrapper(localName = "getObjectValuesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetObjectValuesResponse")
    @RequestWrapper(localName = "getObjectValues", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetObjectValues")
    @WebResult(name = "getObjectValuesReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getObjectValues(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes
    );

    @ResponseWrapper(localName = "loginServiceResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.LoginServiceResponse")
    @RequestWrapper(localName = "loginService", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.LoginService")
    @WebResult(name = "loginServiceReturn", targetNamespace = "")
    @WebMethod
    public int loginService(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "policy", targetNamespace = "")
        java.lang.String policy
    );

    @ResponseWrapper(localName = "closeTicketResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CloseTicketResponse")
    @RequestWrapper(localName = "closeTicket", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CloseTicket")
    @WebResult(name = "closeTicketReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String closeTicket(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "ticketHandle", targetNamespace = "")
        java.lang.String ticketHandle
    );

    @ResponseWrapper(localName = "getDocumentTypesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetDocumentTypesResponse")
    @RequestWrapper(localName = "getDocumentTypes", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetDocumentTypes")
    @WebResult(name = "getDocumentTypesReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getDocumentTypes(
        @WebParam(name = "sid", targetNamespace = "")
        int sid
    );

    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.LogoutResponse")
    @RequestWrapper(localName = "logout", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.Logout")
    @WebMethod
    public void logout(
        @WebParam(name = "sid", targetNamespace = "")
        int sid
    );

    @ResponseWrapper(localName = "getTaskListValuesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetTaskListValuesResponse")
    @RequestWrapper(localName = "getTaskListValues", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetTaskListValues")
    @WebResult(name = "getTaskListValuesReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getTaskListValues(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes
    );

    @ResponseWrapper(localName = "createChangeOrderResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateChangeOrderResponse")
    @RequestWrapper(localName = "createChangeOrder", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateChangeOrder")
    @WebMethod
    public void createChangeOrder(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "creatorHandle", targetNamespace = "")
        java.lang.String creatorHandle,
        @WebParam(name = "attrVals", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attrVals,
        @WebParam(name = "propertyValues", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString propertyValues,
        @WebParam(name = "template", targetNamespace = "")
        java.lang.String template,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newChangeHandle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newChangeHandle,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newChangeNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newChangeNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "createChangeOrderReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> createChangeOrderReturn
    );

    @ResponseWrapper(localName = "getAttmntListResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetAttmntListResponse")
    @RequestWrapper(localName = "getAttmntList", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetAttmntList")
    @WebResult(name = "getAttmntListReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getAttmntList(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "folderId", targetNamespace = "")
        int folderId,
        @WebParam(name = "repId", targetNamespace = "")
        int repId
    );

    @ResponseWrapper(localName = "faqResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.FaqResponse")
    @RequestWrapper(localName = "faq", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.Faq")
    @WebResult(name = "faqReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String faq(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "categoryIds", targetNamespace = "")
        java.lang.String categoryIds,
        @WebParam(name = "resultSize", targetNamespace = "")
        int resultSize,
        @WebParam(name = "propertyList", targetNamespace = "")
        java.lang.String propertyList,
        @WebParam(name = "sortBy", targetNamespace = "")
        java.lang.String sortBy,
        @WebParam(name = "descending", targetNamespace = "")
        boolean descending,
        @WebParam(name = "whereClause", targetNamespace = "")
        java.lang.String whereClause,
        @WebParam(name = "maxDocIDs", targetNamespace = "")
        int maxDocIDs
    );

    @ResponseWrapper(localName = "escalateResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.EscalateResponse")
    @RequestWrapper(localName = "escalate", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.Escalate")
    @WebResult(name = "escalateReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String escalate(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "setAssignee", targetNamespace = "")
        boolean setAssignee,
        @WebParam(name = "newAssigneeHandle", targetNamespace = "")
        java.lang.String newAssigneeHandle,
        @WebParam(name = "setGroup", targetNamespace = "")
        boolean setGroup,
        @WebParam(name = "newGroupHandle", targetNamespace = "")
        java.lang.String newGroupHandle,
        @WebParam(name = "setOrganization", targetNamespace = "")
        boolean setOrganization,
        @WebParam(name = "newOrganizationHandle", targetNamespace = "")
        java.lang.String newOrganizationHandle,
        @WebParam(name = "setPriority", targetNamespace = "")
        boolean setPriority,
        @WebParam(name = "newPriorityHandle", targetNamespace = "")
        java.lang.String newPriorityHandle
    );

    @ResponseWrapper(localName = "getContactResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetContactResponse")
    @RequestWrapper(localName = "getContact", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetContact")
    @WebResult(name = "getContactReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getContact(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contactId", targetNamespace = "")
        java.lang.String contactId
    );

    @ResponseWrapper(localName = "findContactsResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.FindContactsResponse")
    @RequestWrapper(localName = "findContacts", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.FindContacts")
    @WebResult(name = "findContactsReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String findContacts(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "lastName", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "firstName", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "accessType", targetNamespace = "")
        java.lang.String accessType,
        @WebParam(name = "inactiveFlag", targetNamespace = "")
        int inactiveFlag
    );

    @ResponseWrapper(localName = "getBopsidResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetBopsidResponse")
    @RequestWrapper(localName = "getBopsid", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetBopsid")
    @WebResult(name = "getBopsidReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getBopsid(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contact", targetNamespace = "")
        java.lang.String contact
    );

    @ResponseWrapper(localName = "getAssetExtensionInformationResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetAssetExtensionInformationResponse")
    @RequestWrapper(localName = "getAssetExtensionInformation", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetAssetExtensionInformation")
    @WebMethod
    public void getAssetExtensionInformation(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "assetHandle", targetNamespace = "")
        java.lang.String assetHandle,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes,
        @WebParam(mode = WebParam.Mode.INOUT, name = "getAssetExtInfoResult", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> getAssetExtInfoResult,
        @WebParam(mode = WebParam.Mode.INOUT, name = "extensionHandle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> extensionHandle,
        @WebParam(mode = WebParam.Mode.INOUT, name = "extensionName", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> extensionName
    );

    @ResponseWrapper(localName = "deleteWorkFlowTaskResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DeleteWorkFlowTaskResponse")
    @RequestWrapper(localName = "deleteWorkFlowTask", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DeleteWorkFlowTask")
    @WebMethod
    public void deleteWorkFlowTask(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "workFlowHandle", targetNamespace = "")
        java.lang.String workFlowHandle,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle
    );

    @ResponseWrapper(localName = "getCommentsResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetCommentsResponse")
    @RequestWrapper(localName = "getComments", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetComments")
    @WebResult(name = "getCommentsReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getComments(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "docIds", targetNamespace = "")
        java.lang.String docIds
    );

    @ResponseWrapper(localName = "getPendingChangeTaskListForContactResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPendingChangeTaskListForContactResponse")
    @RequestWrapper(localName = "getPendingChangeTaskListForContact", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPendingChangeTaskListForContact")
    @WebResult(name = "getPendingChangeTaskListForContactReturn", targetNamespace = "")
    @WebMethod
    public com.waveset.adapter.ca.ListResult getPendingChangeTaskListForContact(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contactHandle", targetNamespace = "")
        java.lang.String contactHandle
    );

    @ResponseWrapper(localName = "doSelectResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DoSelectResponse")
    @RequestWrapper(localName = "doSelect", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DoSelect")
    @WebResult(name = "doSelectReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String doSelect(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "objectType", targetNamespace = "")
        java.lang.String objectType,
        @WebParam(name = "whereClause", targetNamespace = "")
        java.lang.String whereClause,
        @WebParam(name = "maxRows", targetNamespace = "")
        int maxRows,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes
    );

    @ResponseWrapper(localName = "getAttmntListPerKDResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetAttmntListPerKDResponse")
    @RequestWrapper(localName = "getAttmntListPerKD", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetAttmntListPerKD")
    @WebResult(name = "getAttmntListPerKDReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getAttmntListPerKD(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "docId", targetNamespace = "")
        int docId
    );

    @ResponseWrapper(localName = "getDocumentsByIDsResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetDocumentsByIDsResponse")
    @RequestWrapper(localName = "getDocumentsByIDs", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetDocumentsByIDs")
    @WebResult(name = "getDocumentsByIDsReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getDocumentsByIDs(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "docIds", targetNamespace = "")
        java.lang.String docIds,
        @WebParam(name = "propertyList", targetNamespace = "")
        java.lang.String propertyList,
        @WebParam(name = "sortBy", targetNamespace = "")
        java.lang.String sortBy,
        @WebParam(name = "descending", targetNamespace = "")
        boolean descending
    );

    @ResponseWrapper(localName = "deleteCommentResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DeleteCommentResponse")
    @RequestWrapper(localName = "deleteComment", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DeleteComment")
    @WebResult(name = "deleteCommentReturn", targetNamespace = "")
    @WebMethod
    public int deleteComment(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "commentId", targetNamespace = "")
        int commentId
    );

    @ResponseWrapper(localName = "getTemplateListResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetTemplateListResponse")
    @RequestWrapper(localName = "getTemplateList", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetTemplateList")
    @WebResult(name = "getTemplateListReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getTemplateList(
        @WebParam(name = "sid", targetNamespace = "")
        int sid
    );

    @ResponseWrapper(localName = "notifyContactsResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.NotifyContactsResponse")
    @RequestWrapper(localName = "notifyContacts", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.NotifyContacts")
    @WebResult(name = "notifyContactsReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String notifyContacts(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "contextObject", targetNamespace = "")
        java.lang.String contextObject,
        @WebParam(name = "messageTitle", targetNamespace = "")
        java.lang.String messageTitle,
        @WebParam(name = "messageBody", targetNamespace = "")
        java.lang.String messageBody,
        @WebParam(name = "notifyLevel", targetNamespace = "")
        int notifyLevel,
        @WebParam(name = "notifyees", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString notifyees,
        @WebParam(name = "internal", targetNamespace = "")
        boolean internal
    );

    @ResponseWrapper(localName = "createIssueResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateIssueResponse")
    @RequestWrapper(localName = "createIssue", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateIssue")
    @WebMethod
    public void createIssue(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "creatorHandle", targetNamespace = "")
        java.lang.String creatorHandle,
        @WebParam(name = "attrVals", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attrVals,
        @WebParam(name = "propertyValues", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString propertyValues,
        @WebParam(name = "template", targetNamespace = "")
        java.lang.String template,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newIssueHandle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newIssueHandle,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newIssueNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newIssueNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "createIssueReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> createIssueReturn
    );

    @ResponseWrapper(localName = "getLrelLengthResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetLrelLengthResponse")
    @RequestWrapper(localName = "getLrelLength", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetLrelLength")
    @WebResult(name = "getLrelLengthReturn", targetNamespace = "")
    @WebMethod
    public int getLrelLength(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contextObject", targetNamespace = "")
        java.lang.String contextObject,
        @WebParam(name = "lrelName", targetNamespace = "")
        java.lang.String lrelName
    );

    @ResponseWrapper(localName = "getDocumentResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetDocumentResponse")
    @RequestWrapper(localName = "getDocument", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetDocument")
    @WebResult(name = "getDocumentReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getDocument(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "docId", targetNamespace = "")
        int docId,
        @WebParam(name = "propertyList", targetNamespace = "")
        java.lang.String propertyList,
        @WebParam(name = "relatedDoc", targetNamespace = "")
        boolean relatedDoc,
        @WebParam(name = "getAttmnt", targetNamespace = "")
        boolean getAttmnt,
        @WebParam(name = "getHistory", targetNamespace = "")
        boolean getHistory,
        @WebParam(name = "getComments", targetNamespace = "")
        boolean getComments,
        @WebParam(name = "getNotiList", targetNamespace = "")
        boolean getNotiList
    );

    @ResponseWrapper(localName = "addAssetLogResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AddAssetLogResponse")
    @RequestWrapper(localName = "addAssetLog", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AddAssetLog")
    @WebMethod
    public void addAssetLog(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "assetHandle", targetNamespace = "")
        java.lang.String assetHandle,
        @WebParam(name = "contactHandle", targetNamespace = "")
        java.lang.String contactHandle,
        @WebParam(name = "logText", targetNamespace = "")
        java.lang.String logText
    );

    @ResponseWrapper(localName = "getAttmntInfoResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetAttmntInfoResponse")
    @RequestWrapper(localName = "getAttmntInfo", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetAttmntInfo")
    @WebResult(name = "getAttmntInfoReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getAttmntInfo(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "attmntId", targetNamespace = "")
        int attmntId
    );

    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.LoginResponse")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.Login")
    @WebResult(name = "loginReturn", targetNamespace = "")
    @WebMethod
    public int login(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @ResponseWrapper(localName = "getStatusesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetStatusesResponse")
    @RequestWrapper(localName = "getStatuses", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetStatuses")
    @WebResult(name = "getStatusesReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getStatuses(
        @WebParam(name = "sid", targetNamespace = "")
        int sid
    );

    @ResponseWrapper(localName = "getCategoryResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetCategoryResponse")
    @RequestWrapper(localName = "getCategory", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetCategory")
    @WebResult(name = "getCategoryReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getCategory(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "catId", targetNamespace = "")
        int catId,
        @WebParam(name = "getCategoryPaths", targetNamespace = "")
        boolean getCategoryPaths
    );

    @ResponseWrapper(localName = "getConfigurationModeResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetConfigurationModeResponse")
    @RequestWrapper(localName = "getConfigurationMode", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetConfigurationMode")
    @WebResult(name = "getConfigurationModeReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getConfigurationMode(
        @WebParam(name = "sid", targetNamespace = "")
        int sid
    );

    @ResponseWrapper(localName = "modifyDocumentResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.ModifyDocumentResponse")
    @RequestWrapper(localName = "modifyDocument", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.ModifyDocument")
    @WebResult(name = "modifyDocumentReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String modifyDocument(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "docId", targetNamespace = "")
        int docId,
        @WebParam(name = "kdAttributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString kdAttributes
    );

    @ResponseWrapper(localName = "attmntFolderLinkCountResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AttmntFolderLinkCountResponse")
    @RequestWrapper(localName = "attmntFolderLinkCount", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AttmntFolderLinkCount")
    @WebResult(name = "attmntFolderLinkCountReturn", targetNamespace = "")
    @WebMethod
    public int attmntFolderLinkCount(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "folderId", targetNamespace = "")
        int folderId
    );

    @ResponseWrapper(localName = "getNotificationsForContactResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetNotificationsForContactResponse")
    @RequestWrapper(localName = "getNotificationsForContact", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetNotificationsForContact")
    @WebResult(name = "getNotificationsForContactReturn", targetNamespace = "")
    @WebMethod
    public com.waveset.adapter.ca.ListResult getNotificationsForContact(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contactHandle", targetNamespace = "")
        java.lang.String contactHandle,
        @WebParam(name = "queryStatus", targetNamespace = "")
        int queryStatus
    );

    @ResponseWrapper(localName = "getHandleForUseridResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetHandleForUseridResponse")
    @RequestWrapper(localName = "getHandleForUserid", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetHandleForUserid")
    @WebResult(name = "getHandleForUseridReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getHandleForUserid(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "userID", targetNamespace = "")
        java.lang.String userID
    );

    @ResponseWrapper(localName = "createQuickTicketResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateQuickTicketResponse")
    @RequestWrapper(localName = "createQuickTicket", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateQuickTicket")
    @WebMethod
    public void createQuickTicket(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "customerHandle", targetNamespace = "")
        java.lang.String customerHandle,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newTicketHandle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newTicketHandle,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newTicketNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newTicketNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "createQuickTicketReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> createQuickTicketReturn
    );

    @ResponseWrapper(localName = "isAttmntLinkedKDResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.IsAttmntLinkedKDResponse")
    @RequestWrapper(localName = "isAttmntLinkedKD", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.IsAttmntLinkedKD")
    @WebResult(name = "isAttmntLinkedKDReturn", targetNamespace = "")
    @WebMethod
    public int isAttmntLinkedKD(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "attmntId", targetNamespace = "")
        int attmntId
    );

    @ResponseWrapper(localName = "attachChangeToRequestResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AttachChangeToRequestResponse")
    @RequestWrapper(localName = "attachChangeToRequest", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AttachChangeToRequest")
    @WebResult(name = "attachChangeToRequestReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String attachChangeToRequest(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "requestHandle", targetNamespace = "")
        java.lang.String requestHandle,
        @WebParam(name = "changeHandle", targetNamespace = "")
        java.lang.String changeHandle,
        @WebParam(name = "changeAttrVals", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString changeAttrVals,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description
    );

    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.SearchResponse")
    @RequestWrapper(localName = "search", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.Search")
    @WebResult(name = "searchReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String search(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "problem", targetNamespace = "")
        java.lang.String problem,
        @WebParam(name = "resultSize", targetNamespace = "")
        int resultSize,
        @WebParam(name = "properties", targetNamespace = "")
        java.lang.String properties,
        @WebParam(name = "sortBy", targetNamespace = "")
        java.lang.String sortBy,
        @WebParam(name = "descending", targetNamespace = "")
        boolean descending,
        @WebParam(name = "relatedCategories", targetNamespace = "")
        boolean relatedCategories,
        @WebParam(name = "searchType", targetNamespace = "")
        int searchType,
        @WebParam(name = "matchType", targetNamespace = "")
        int matchType,
        @WebParam(name = "searchField", targetNamespace = "")
        int searchField,
        @WebParam(name = "categoryPath", targetNamespace = "")
        java.lang.String categoryPath,
        @WebParam(name = "whereClause", targetNamespace = "")
        java.lang.String whereClause,
        @WebParam(name = "maxDocIDs", targetNamespace = "")
        int maxDocIDs
    );

    @ResponseWrapper(localName = "impersonateResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.ImpersonateResponse")
    @RequestWrapper(localName = "impersonate", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.Impersonate")
    @WebResult(name = "impersonateReturn", targetNamespace = "")
    @WebMethod
    public int impersonate(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "userid", targetNamespace = "")
        java.lang.String userid
    );

    @ResponseWrapper(localName = "addCommentResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AddCommentResponse")
    @RequestWrapper(localName = "addComment", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AddComment")
    @WebResult(name = "addCommentReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String addComment(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "comment", targetNamespace = "")
        java.lang.String comment,
        @WebParam(name = "docId", targetNamespace = "")
        int docId,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "contactId", targetNamespace = "")
        java.lang.String contactId
    );

    @ResponseWrapper(localName = "clearNotificationResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.ClearNotificationResponse")
    @RequestWrapper(localName = "clearNotification", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.ClearNotification")
    @WebResult(name = "clearNotificationReturn", targetNamespace = "")
    @WebMethod
    public int clearNotification(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "lrObject", targetNamespace = "")
        java.lang.String lrObject,
        @WebParam(name = "clearBy", targetNamespace = "")
        java.lang.String clearBy
    );

    @ResponseWrapper(localName = "createLrelRelationshipsResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateLrelRelationshipsResponse")
    @RequestWrapper(localName = "createLrelRelationships", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateLrelRelationships")
    @WebMethod
    public void createLrelRelationships(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contextObject", targetNamespace = "")
        java.lang.String contextObject,
        @WebParam(name = "lrelName", targetNamespace = "")
        java.lang.String lrelName,
        @WebParam(name = "addObjectHandles", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString addObjectHandles
    );

    @ResponseWrapper(localName = "getPendingIssueTaskListForContactResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPendingIssueTaskListForContactResponse")
    @RequestWrapper(localName = "getPendingIssueTaskListForContact", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPendingIssueTaskListForContact")
    @WebResult(name = "getPendingIssueTaskListForContactReturn", targetNamespace = "")
    @WebMethod
    public com.waveset.adapter.ca.ListResult getPendingIssueTaskListForContact(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contactHandle", targetNamespace = "")
        java.lang.String contactHandle
    );

    @ResponseWrapper(localName = "deleteDocumentResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DeleteDocumentResponse")
    @RequestWrapper(localName = "deleteDocument", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DeleteDocument")
    @WebResult(name = "deleteDocumentReturn", targetNamespace = "")
    @WebMethod
    public int deleteDocument(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "docId", targetNamespace = "")
        int docId
    );

    @ResponseWrapper(localName = "getPolicyInfoResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPolicyInfoResponse")
    @RequestWrapper(localName = "getPolicyInfo", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPolicyInfo")
    @WebResult(name = "getPolicyInfoReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getPolicyInfo(
        @WebParam(name = "sid", targetNamespace = "")
        int sid
    );

    @ResponseWrapper(localName = "createRequestResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateRequestResponse")
    @RequestWrapper(localName = "createRequest", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateRequest")
    @WebMethod
    public void createRequest(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "creatorHandle", targetNamespace = "")
        java.lang.String creatorHandle,
        @WebParam(name = "attrVals", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attrVals,
        @WebParam(name = "propertyValues", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString propertyValues,
        @WebParam(name = "template", targetNamespace = "")
        java.lang.String template,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newRequestHandle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newRequestHandle,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newRequestNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newRequestNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "createRequestReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> createRequestReturn
    );

    @ResponseWrapper(localName = "getWorkflowTemplateListResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetWorkflowTemplateListResponse")
    @RequestWrapper(localName = "getWorkflowTemplateList", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetWorkflowTemplateList")
    @WebResult(name = "getWorkflowTemplateListReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getWorkflowTemplateList(
        @WebParam(name = "sid", targetNamespace = "")
        int sid
    );

    @ResponseWrapper(localName = "removeLrelRelationshipsResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.RemoveLrelRelationshipsResponse")
    @RequestWrapper(localName = "removeLrelRelationships", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.RemoveLrelRelationships")
    @WebMethod
    public void removeLrelRelationships(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contextObject", targetNamespace = "")
        java.lang.String contextObject,
        @WebParam(name = "lrelName", targetNamespace = "")
        java.lang.String lrelName,
        @WebParam(name = "removeObjectHandles", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString removeObjectHandles
    );

    @ResponseWrapper(localName = "getRelatedListValuesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetRelatedListValuesResponse")
    @RequestWrapper(localName = "getRelatedListValues", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetRelatedListValues")
    @WebMethod
    public void getRelatedListValues(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "listName", targetNamespace = "")
        java.lang.String listName,
        @WebParam(name = "numToFetch", targetNamespace = "")
        int numToFetch,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes,
        @WebParam(mode = WebParam.Mode.INOUT, name = "getRelatedListValuesResult", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> getRelatedListValuesResult,
        @WebParam(mode = WebParam.Mode.INOUT, name = "numRowsFound", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> numRowsFound
    );

    @ResponseWrapper(localName = "createObjectResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateObjectResponse")
    @RequestWrapper(localName = "createObject", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateObject")
    @WebMethod
    public void createObject(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "objectType", targetNamespace = "")
        java.lang.String objectType,
        @WebParam(name = "attrVals", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attrVals,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes,
        @WebParam(mode = WebParam.Mode.INOUT, name = "createObjectResult", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> createObjectResult,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newHandle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newHandle
    );

    @ResponseWrapper(localName = "getKDListPerAttmntResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetKDListPerAttmntResponse")
    @RequestWrapper(localName = "getKDListPerAttmnt", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetKDListPerAttmnt")
    @WebResult(name = "getKDListPerAttmntReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getKDListPerAttmnt(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "attmntId", targetNamespace = "")
        int attmntId
    );

    @ResponseWrapper(localName = "getDecisionTreesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetDecisionTreesResponse")
    @RequestWrapper(localName = "getDecisionTrees", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetDecisionTrees")
    @WebResult(name = "getDecisionTreesReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getDecisionTrees(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "propertyList", targetNamespace = "")
        java.lang.String propertyList,
        @WebParam(name = "sortBy", targetNamespace = "")
        java.lang.String sortBy,
        @WebParam(name = "descending", targetNamespace = "")
        boolean descending
    );

    @ResponseWrapper(localName = "detachChangeFromRequestResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DetachChangeFromRequestResponse")
    @RequestWrapper(localName = "detachChangeFromRequest", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DetachChangeFromRequest")
    @WebResult(name = "detachChangeFromRequestReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String detachChangeFromRequest(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "requestHandle", targetNamespace = "")
        java.lang.String requestHandle,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description
    );

    @ResponseWrapper(localName = "getRelatedListResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetRelatedListResponse")
    @RequestWrapper(localName = "getRelatedList", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetRelatedList")
    @WebResult(name = "getRelatedListReturn", targetNamespace = "")
    @WebMethod
    public com.waveset.adapter.ca.ListResult getRelatedList(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "listName", targetNamespace = "")
        java.lang.String listName
    );

    @ResponseWrapper(localName = "logCommentResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.LogCommentResponse")
    @RequestWrapper(localName = "logComment", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.LogComment")
    @WebMethod
    public void logComment(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "ticketHandle", targetNamespace = "")
        java.lang.String ticketHandle,
        @WebParam(name = "comment", targetNamespace = "")
        java.lang.String comment,
        @WebParam(name = "internalFlag", targetNamespace = "")
        int internalFlag
    );

    @ResponseWrapper(localName = "updateObjectResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.UpdateObjectResponse")
    @RequestWrapper(localName = "updateObject", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.UpdateObject")
    @WebResult(name = "updateObjectReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String updateObject(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "attrVals", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attrVals,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes
    );

    @ResponseWrapper(localName = "getObjectTypeInformationResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetObjectTypeInformationResponse")
    @RequestWrapper(localName = "getObjectTypeInformation", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetObjectTypeInformation")
    @WebResult(name = "getObjectTypeInformationReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getObjectTypeInformation(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "factory", targetNamespace = "")
        java.lang.String factory
    );

    @ResponseWrapper(localName = "createTicketResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateTicketResponse")
    @RequestWrapper(localName = "createTicket", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateTicket")
    @WebMethod
    public void createTicket(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "problem_type", targetNamespace = "")
        java.lang.String problemType,
        @WebParam(name = "userid", targetNamespace = "")
        java.lang.String userid,
        @WebParam(name = "asset", targetNamespace = "")
        java.lang.String asset,
        @WebParam(name = "duplication_id", targetNamespace = "")
        java.lang.String duplicationId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newTicketHandle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newTicketHandle,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newTicketNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newTicketNumber,
        @WebParam(mode = WebParam.Mode.INOUT, name = "returnUserData", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> returnUserData,
        @WebParam(mode = WebParam.Mode.INOUT, name = "returnApplicationData", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> returnApplicationData,
        @WebParam(mode = WebParam.Mode.OUT, name = "createTicketReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> createTicketReturn
    );

    @ResponseWrapper(localName = "getFolderListResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetFolderListResponse")
    @RequestWrapper(localName = "getFolderList", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetFolderList")
    @WebResult(name = "getFolderListReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getFolderList(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "parentFolderId", targetNamespace = "")
        int parentFolderId,
        @WebParam(name = "repId", targetNamespace = "")
        int repId
    );

    @ResponseWrapper(localName = "createFolderResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateFolderResponse")
    @RequestWrapper(localName = "createFolder", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateFolder")
    @WebResult(name = "createFolderReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String createFolder(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "parentFolderId", targetNamespace = "")
        int parentFolderId,
        @WebParam(name = "repId", targetNamespace = "")
        int repId,
        @WebParam(name = "folderType", targetNamespace = "")
        int folderType,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "folderName", targetNamespace = "")
        java.lang.String folderName
    );

    @ResponseWrapper(localName = "getListValuesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetListValuesResponse")
    @RequestWrapper(localName = "getListValues", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetListValues")
    @WebResult(name = "getListValuesReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getListValues(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "listHandle", targetNamespace = "")
        int listHandle,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "endIndex", targetNamespace = "")
        int endIndex,
        @WebParam(name = "attributeNames", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributeNames
    );

    @ResponseWrapper(localName = "attachURLLinkResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AttachURLLinkResponse")
    @RequestWrapper(localName = "attachURLLink", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AttachURLLink")
    @WebResult(name = "attachURLLinkReturn", targetNamespace = "")
    @WebMethod
    public int attachURLLink(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "docId", targetNamespace = "")
        int docId,
        @WebParam(name = "url", targetNamespace = "")
        java.lang.String url,
        @WebParam(name = "attmntName", targetNamespace = "")
        java.lang.String attmntName,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description
    );

    @ResponseWrapper(localName = "doQueryResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DoQueryResponse")
    @RequestWrapper(localName = "doQuery", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.DoQuery")
    @WebResult(name = "doQueryReturn", targetNamespace = "")
    @WebMethod
    public com.waveset.adapter.ca.ListResult doQuery(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "objectType", targetNamespace = "")
        java.lang.String objectType,
        @WebParam(name = "whereClause", targetNamespace = "")
        java.lang.String whereClause
    );

    @ResponseWrapper(localName = "createAssetResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateAssetResponse")
    @RequestWrapper(localName = "createAsset", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateAsset")
    @WebMethod
    public void createAsset(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "attrVals", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attrVals,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes,
        @WebParam(mode = WebParam.Mode.INOUT, name = "createAssetResult", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> createAssetResult,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newAssetHandle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newAssetHandle,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newExtensionHandle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newExtensionHandle,
        @WebParam(mode = WebParam.Mode.INOUT, name = "newExtensionName", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> newExtensionName
    );

    @ResponseWrapper(localName = "getPermissionGroupsResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPermissionGroupsResponse")
    @RequestWrapper(localName = "getPermissionGroups", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPermissionGroups")
    @WebResult(name = "getPermissionGroupsReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getPermissionGroups(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "groupId", targetNamespace = "")
        int groupId
    );

    @ResponseWrapper(localName = "getAccessTypeForContactResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetAccessTypeForContactResponse")
    @RequestWrapper(localName = "getAccessTypeForContact", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetAccessTypeForContact")
    @WebResult(name = "getAccessTypeForContactReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getAccessTypeForContact(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contactHandle", targetNamespace = "")
        java.lang.String contactHandle
    );

    @ResponseWrapper(localName = "updateRatingResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.UpdateRatingResponse")
    @RequestWrapper(localName = "updateRating", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.UpdateRating")
    @WebResult(name = "updateRatingReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String updateRating(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "buId", targetNamespace = "")
        int buId,
        @WebParam(name = "rate", targetNamespace = "")
        int rate
    );

    @ResponseWrapper(localName = "addBookmarkResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AddBookmarkResponse")
    @RequestWrapper(localName = "addBookmark", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AddBookmark")
    @WebResult(name = "addBookmarkReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String addBookmark(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contactId", targetNamespace = "")
        java.lang.String contactId,
        @WebParam(name = "docId", targetNamespace = "")
        int docId
    );

    @ResponseWrapper(localName = "createDocumentResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateDocumentResponse")
    @RequestWrapper(localName = "createDocument", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CreateDocument")
    @WebResult(name = "createDocumentReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String createDocument(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "kdAttributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString kdAttributes
    );

    @ResponseWrapper(localName = "freeListHandlesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.FreeListHandlesResponse")
    @RequestWrapper(localName = "freeListHandles", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.FreeListHandles")
    @WebMethod
    public void freeListHandles(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "handles", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfInt handles
    );

    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.TransferResponse")
    @RequestWrapper(localName = "transfer", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.Transfer")
    @WebResult(name = "transferReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String transfer(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "setAssignee", targetNamespace = "")
        boolean setAssignee,
        @WebParam(name = "newAssigneeHandle", targetNamespace = "")
        java.lang.String newAssigneeHandle,
        @WebParam(name = "setGroup", targetNamespace = "")
        boolean setGroup,
        @WebParam(name = "newGroupHandle", targetNamespace = "")
        java.lang.String newGroupHandle,
        @WebParam(name = "setOrganization", targetNamespace = "")
        boolean setOrganization,
        @WebParam(name = "newOrganizationHandle", targetNamespace = "")
        java.lang.String newOrganizationHandle
    );

    @ResponseWrapper(localName = "serverStatusResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.ServerStatusResponse")
    @RequestWrapper(localName = "serverStatus", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.ServerStatus")
    @WebResult(name = "serverStatusReturn", targetNamespace = "")
    @WebMethod
    public int serverStatus(
        @WebParam(name = "sid", targetNamespace = "")
        int sid
    );

    @ResponseWrapper(localName = "getRepositoryInfoResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetRepositoryInfoResponse")
    @RequestWrapper(localName = "getRepositoryInfo", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetRepositoryInfo")
    @WebResult(name = "getRepositoryInfoReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getRepositoryInfo(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "repositoryId", targetNamespace = "")
        int repositoryId
    );

    @ResponseWrapper(localName = "getValidTaskTransitionsResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetValidTaskTransitionsResponse")
    @RequestWrapper(localName = "getValidTaskTransitions", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetValidTaskTransitions")
    @WebResult(name = "getValidTaskTransitionsReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getValidTaskTransitions(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "taskHandle", targetNamespace = "")
        java.lang.String taskHandle,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes
    );

    @ResponseWrapper(localName = "changeStatusResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.ChangeStatusResponse")
    @RequestWrapper(localName = "changeStatus", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.ChangeStatus")
    @WebResult(name = "changeStatusReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String changeStatus(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "objectHandle", targetNamespace = "")
        java.lang.String objectHandle,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "newStatusHandle", targetNamespace = "")
        java.lang.String newStatusHandle
    );

    @ResponseWrapper(localName = "callServerMethodResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CallServerMethodResponse")
    @RequestWrapper(localName = "callServerMethod", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.CallServerMethod")
    @WebResult(name = "callServerMethodReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String callServerMethod(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "methodName", targetNamespace = "")
        java.lang.String methodName,
        @WebParam(name = "factoryName", targetNamespace = "")
        java.lang.String factoryName,
        @WebParam(name = "formatList", targetNamespace = "")
        java.lang.String formatList,
        @WebParam(name = "parameters", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString parameters
    );

    @ResponseWrapper(localName = "removeAttachmentResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.RemoveAttachmentResponse")
    @RequestWrapper(localName = "removeAttachment", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.RemoveAttachment")
    @WebResult(name = "removeAttachmentReturn", targetNamespace = "")
    @WebMethod
    public int removeAttachment(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "attHandle", targetNamespace = "")
        java.lang.String attHandle
    );

    @ResponseWrapper(localName = "rateDocumentResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.RateDocumentResponse")
    @RequestWrapper(localName = "rateDocument", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.RateDocument")
    @WebResult(name = "rateDocumentReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String rateDocument(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "docId", targetNamespace = "")
        int docId,
        @WebParam(name = "rating", targetNamespace = "")
        int rating,
        @WebParam(name = "multiplier", targetNamespace = "")
        int multiplier,
        @WebParam(name = "ticketPerId", targetNamespace = "")
        java.lang.String ticketPerId,
        @WebParam(name = "onTicketAccept", targetNamespace = "")
        boolean onTicketAccept,
        @WebParam(name = "solveUserProblem", targetNamespace = "")
        boolean solveUserProblem,
        @WebParam(name = "isDefault", targetNamespace = "")
        boolean isDefault
    );

    @ResponseWrapper(localName = "getPrioritiesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPrioritiesResponse")
    @RequestWrapper(localName = "getPriorities", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetPriorities")
    @WebResult(name = "getPrioritiesReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getPriorities(
        @WebParam(name = "sid", targetNamespace = "")
        int sid
    );

    @ResponseWrapper(localName = "getGroupMemberListValuesResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetGroupMemberListValuesResponse")
    @RequestWrapper(localName = "getGroupMemberListValues", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetGroupMemberListValues")
    @WebResult(name = "getGroupMemberListValuesReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getGroupMemberListValues(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "whereClause", targetNamespace = "")
        java.lang.String whereClause,
        @WebParam(name = "numToFetch", targetNamespace = "")
        int numToFetch,
        @WebParam(name = "attributes", targetNamespace = "")
        com.waveset.adapter.ca.ArrayOfString attributes
    );

    @ResponseWrapper(localName = "getQuestionsAskedResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetQuestionsAskedResponse")
    @RequestWrapper(localName = "getQuestionsAsked", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.GetQuestionsAsked")
    @WebResult(name = "getQuestionsAskedReturn", targetNamespace = "")
    @WebMethod
    public java.lang.String getQuestionsAsked(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "resultSize", targetNamespace = "")
        int resultSize,
        @WebParam(name = "descending", targetNamespace = "")
        boolean descending
    );

    @ResponseWrapper(localName = "addMemberToGroupResponse", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AddMemberToGroupResponse")
    @RequestWrapper(localName = "addMemberToGroup", targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk", className = "com.waveset.adapter.ca.AddMemberToGroup")
    @WebMethod
    public void addMemberToGroup(
        @WebParam(name = "sid", targetNamespace = "")
        int sid,
        @WebParam(name = "contactHandle", targetNamespace = "")
        java.lang.String contactHandle,
        @WebParam(name = "groupHandle", targetNamespace = "")
        java.lang.String groupHandle
    );
}
