
/*
 * 
 */

package com.waveset.adapter.ca;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Sep 24 10:58:37 CEST 2009
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "USD_WebService", 
                  wsdlLocation = "file:USD_R11_WebService.xml",
                  targetNamespace = "http://www.ca.com/UnicenterServicePlus/ServiceDesk") 
public class USDWebService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.ca.com/UnicenterServicePlus/ServiceDesk", "USD_WebService");
    public final static QName USDWebServiceSoap = new QName("http://www.ca.com/UnicenterServicePlus/ServiceDesk", "USD_WebServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:USD_R11_WebService.xml");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:USD_R11_WebService.xml");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public USDWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public USDWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public USDWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns USDWebServiceSoap
     */
    @WebEndpoint(name = "USD_WebServiceSoap")
    public USDWebServiceSoap getUSDWebServiceSoap() {
        return super.getPort(USDWebServiceSoap, USDWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns USDWebServiceSoap
     */
    @WebEndpoint(name = "USD_WebServiceSoap")
    public USDWebServiceSoap getUSDWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(USDWebServiceSoap, USDWebServiceSoap.class, features);
    }

}
